### ISSUE TITLE
C2V can't find header files from parent folder.

### ISSUE THREAD

**Issue by ComradeCat1** [vlang/c2v#129]
I ran the following command in a CPython repository that I cloned locally on my computer:
v translate .
C to V translator 0.3.1
"." is a directory, processing all C files in it recursively...

  translating .\Doc\includes\custom.c ... .\Doc\includes\custom.c:2:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^~~~~~~~~~
1 error generated.

The file .\Doc\includes\custom.c could not be parsed as a C source file.
C2V command: "C:\Users\tudor\.vmodules\c2v\c2v.exe" "."
C2V failed to translate the C files. Please report it via GitHub.

Python.h isn't in the Doc folder, it's in <path_to_cpython_repo>/Include/Python.h/
How do I tell the C2V translator where the header files are?
I simply want to specify that C header files are located in the Include folder.
Who knows? Maybe the CPython codebase isn't meant to be translated to V.

**Comment by ComradeCat1** [comment]
Oh, it's a problem with Clang

**Comment by ArtemkaKun** [comment]
Hi, you need to set up a configuration file to achieve that. See -> https://github.com/vlang/c2v#configuration

**Comment by ComradeCat1** [comment]
Oh, sorry for making a useless issue. I will close it now.

**Comment by ArtemkaKun** [comment]
@ComradeCat1 

It's not useless, just make sure the configuration thing works for you (it should). If it not - reopen/create a new issue
