### ISSUE TITLE
Unhandled expr() node {FullComment} (ast line nr node.ast_line_nr ):

### ISSUE THREAD

**Issue by Shinyzenith** [vlang/c2v#47]
Full error log: http://0x0.st/o1yY.txt
Source code: https://git.sr.ht/~shinyzenith/NextWM/tree/master/item/nextctl/nextctl.c

**Comment by ArtemkaKun** [comment]
I think this is a duplicate of #4. 
What if you will remove all comments from your code and try again?

**Comment by Shinyzenith** [comment]
> I think this is a duplicate of #4. 
> What if you will remove all comments from your code and try again?
Removing comments fixes the issue.

**Comment by medvednikov** [comment]
@ArtemkaKun #4 was fixed 4 hours ago, but this issue still remains. It should be open then.

**Comment by ArtemkaKun** [comment]
Sorry, I messed up. It's duplicate of #3 :)
