### ISSUE TITLE
Functions with uppercases are wrongly wrap

### ISSUE THREAD

**Issue by dedesite** [vlang/c2v#61]
When calling `c2v wrapper test.h` on this file :
```c
void testFunc() {
    
}
```
It generates this file :
```v
[translated]
module .

fn C.testFunc() 

pub [c:'testFunc']
fn testfunc()  {
        C.testfunc()
}
```

There is two errors here : 
- `pub` keyword should be right before the `fn` keyword
- the call to `C.testfunc()` should be `C.testFunc()`

**Comment by ArtemkaKun** [comment]
Fixed in #63
